// Code generated by bin/gen-service-uuids; DO NOT EDIT.
// This file was generated on 2025-01-13 18:36:59.761153799 -0700 MST m=+0.000624668 using the list of standard service UUIDs from
// https://github.com/NordicSemiconductor/bluetooth-numbers-database/blob/master/v1/service_uuids.json
//
package bluetooth

type ServiceInfo struct {
	Name       string
	Identifier string
	UUID       UUID
	Source     string
}

var (
	ServiceesInfoByUUID = make(map[UUID]ServiceInfo, 123)

	// ServiceUUIDPublicBroadcastAnnouncement - Public Broadcast Announcement
	ServiceUUIDPublicBroadcastAnnouncement = New16BitUUID(0x1856)

	// ServiceUUIDAdafruitMagnetometer - Adafruit Magnetometer Service
	ServiceUUIDAdafruitMagnetometer = NewUUID([16]byte{0xad,0xaf,0x05,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDNextDSTChange - Next DST Change Service
	ServiceUUIDNextDSTChange = New16BitUUID(0x1807)

	// ServiceUUIDImmediateAlert - Immediate Alert
	ServiceUUIDImmediateAlert = New16BitUUID(0x1802)

	// ServiceUUIDMeshProvisioning - Mesh Provisioning Service
	ServiceUUIDMeshProvisioning = New16BitUUID(0x1827)

	// ServiceUUIDThingySound - Thingy Sound Service
	ServiceUUIDThingySound = NewUUID([16]byte{0xef,0x68,0x05,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,})

	// ServiceUUIDEddystone - Eddystone
	ServiceUUIDEddystone = New16BitUUID(0xFEAA)

	// ServiceUUIDDeviceInformation - Device Information
	ServiceUUIDDeviceInformation = New16BitUUID(0x180A)

	// ServiceUUIDInternetProtocolSupport - Internet Protocol Support Service
	ServiceUUIDInternetProtocolSupport = New16BitUUID(0x1820)

	// ServiceUUIDMicrobitAccelerometer - micro:bit Accelerometer Service
	ServiceUUIDMicrobitAccelerometer = NewUUID([16]byte{0xe9,0x5d,0x07,0x53,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})

	// ServiceUUIDThingyMotion - Thingy Motion Service
	ServiceUUIDThingyMotion = NewUUID([16]byte{0xef,0x68,0x04,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,})

	// ServiceUUIDAdafruitSound - Adafruit Sound Service
	ServiceUUIDAdafruitSound = NewUUID([16]byte{0xad,0xaf,0x0b,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDGenericMediaControl - Generic Media Control
	ServiceUUIDGenericMediaControl = New16BitUUID(0x1849)

	// ServiceUUIDAutomationIO - Automation IO
	ServiceUUIDAutomationIO = New16BitUUID(0x1815)

	// ServiceUUIDAudioStreamControl - Audio Stream Control
	ServiceUUIDAudioStreamControl = New16BitUUID(0x184E)

	// ServiceUUIDMicrobitEvent - micro:bit Event Service
	ServiceUUIDMicrobitEvent = NewUUID([16]byte{0xe9,0x5d,0x93,0xaf,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})

	// ServiceUUIDHumanInterfaceDevice - Human Interface Device
	ServiceUUIDHumanInterfaceDevice = New16BitUUID(0x1812)

	// ServiceUUIDHearingAccess - Hearing Access
	ServiceUUIDHearingAccess = New16BitUUID(0x1854)

	// ServiceUUIDBattery - Battery Service
	ServiceUUIDBattery = New16BitUUID(0x180F)

	// ServiceUUIDBroadcastAudioAnnouncement - Broadcast Audio Announcement
	ServiceUUIDBroadcastAudioAnnouncement = New16BitUUID(0x1852)

	// ServiceUUIDCommonAudio - Common Audio
	ServiceUUIDCommonAudio = New16BitUUID(0x1853)

	// ServiceUUIDGenericAccess - Generic Access
	ServiceUUIDGenericAccess = New16BitUUID(0x1800)

	// ServiceUUIDSignifyNetherlandsBVFormerlyPhilipsLighting - Signify Netherlands B.V. (formerly Philips Lighting) Service
	ServiceUUIDSignifyNetherlandsBVFormerlyPhilipsLighting = New16BitUUID(0xFE0F)

	// ServiceUUIDEdgeImpulseRemoteManagement - Edge Impulse Remote Management Service
	ServiceUUIDEdgeImpulseRemoteManagement = NewUUID([16]byte{0xe2,0xa0,0x00,0x01,0xec,0x31,0x4e,0xc3,0xa9,0x7a,0x1c,0x34,0xd8,0x7e,0x98,0x78,})

	// ServiceUUIDAdafruitBarometric - Adafruit Barometric Service
	ServiceUUIDAdafruitBarometric = NewUUID([16]byte{0xad,0xaf,0x08,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDAlertNotification - Alert Notification Service
	ServiceUUIDAlertNotification = New16BitUUID(0x1811)

	// ServiceUUIDWeightScale - Weight Scale
	ServiceUUIDWeightScale = New16BitUUID(0x181D)

	// ServiceUUIDEmergencyConfiguration - Emergency Configuration
	ServiceUUIDEmergencyConfiguration = New16BitUUID(0x183C)

	// ServiceUUIDPhilipsHueLightUpdate - Philips Hue Light Update Service
	ServiceUUIDPhilipsHueLightUpdate = NewUUID([16]byte{0xb8,0x84,0x3a,0xdd,0x00,0x00,0x4a,0xa1,0x87,0x94,0xc3,0xf4,0x62,0x03,0x0b,0xda,})

	// ServiceUUIDAdafruitProximity - Adafruit Proximity Service
	ServiceUUIDAdafruitProximity = NewUUID([16]byte{0xad,0xaf,0x0e,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDInsulinDelivery - Insulin Delivery
	ServiceUUIDInsulinDelivery = New16BitUUID(0x183A)

	// ServiceUUIDTelephonyAndMediaAudio - Telephony and Media Audio
	ServiceUUIDTelephonyAndMediaAudio = New16BitUUID(0x1855)

	// ServiceUUIDMicrobitIOPin - micro:bit IO Pin Service
	ServiceUUIDMicrobitIOPin = NewUUID([16]byte{0xe9,0x5d,0x12,0x7b,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})

	// ServiceUUIDLEGOWirelessProtocolV3Hub - LEGO® Wireless Protocol v3 Hub Service
	ServiceUUIDLEGOWirelessProtocolV3Hub = NewUUID([16]byte{0x00,0x00,0x16,0x23,0x12,0x12,0xef,0xde,0x16,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,})

	// ServiceUUIDRunningSpeedAndCadence - Running Speed and Cadence
	ServiceUUIDRunningSpeedAndCadence = New16BitUUID(0x1814)

	// ServiceUUIDBroadcastAudioScan - Broadcast Audio Scan
	ServiceUUIDBroadcastAudioScan = New16BitUUID(0x184F)

	// ServiceUUIDSMP - SMP Service
	ServiceUUIDSMP = NewUUID([16]byte{0x8d,0x53,0xdc,0x1d,0x1d,0xb7,0x4c,0xd3,0x86,0x8b,0x8a,0x52,0x74,0x60,0xaa,0x84,})

	// ServiceUUIDAdafruitQuaternion - Adafruit Quaternion Service
	ServiceUUIDAdafruitQuaternion = NewUUID([16]byte{0xad,0xaf,0x0d,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDMemfaultDiagnostic - Memfault Diagnostic Service
	ServiceUUIDMemfaultDiagnostic = NewUUID([16]byte{0x54,0x22,0x00,0x00,0xf6,0xa5,0x40,0x07,0xa3,0x71,0x72,0x2f,0x4e,0xbd,0x84,0x36,})

	// ServiceUUIDBondManagement - Bond Management Service
	ServiceUUIDBondManagement = New16BitUUID(0x181E)

	// ServiceUUIDAppleReserved1 - Apple Reserved Service 1
	ServiceUUIDAppleReserved1 = NewUUID([16]byte{0x7d,0xfc,0x60,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,})

	// ServiceUUIDAppleReserved2 - Apple Reserved Service 2
	ServiceUUIDAppleReserved2 = NewUUID([16]byte{0x7d,0xfc,0x70,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,})

	// ServiceUUIDAppleReserved3 - Apple Reserved Service 3
	ServiceUUIDAppleReserved3 = NewUUID([16]byte{0x7d,0xfc,0x80,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,})

	// ServiceUUIDAppleReserved4 - Apple Reserved Service 4
	ServiceUUIDAppleReserved4 = NewUUID([16]byte{0x7d,0xfc,0x90,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,})

	// ServiceUUIDThingyWeatherStation - Thingy Weather Station Service
	ServiceUUIDThingyWeatherStation = NewUUID([16]byte{0xef,0x68,0x02,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,})

	// ServiceUUIDFitnessMachine - Fitness Machine
	ServiceUUIDFitnessMachine = New16BitUUID(0x1826)

	// ServiceUUIDAdafruitAddressable - Adafruit Addressable Service
	ServiceUUIDAdafruitAddressable = NewUUID([16]byte{0xad,0xaf,0x09,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDAdafruitTone - Adafruit Tone Service
	ServiceUUIDAdafruitTone = NewUUID([16]byte{0xad,0xaf,0x0c,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDCurrentTime - Current Time Service
	ServiceUUIDCurrentTime = New16BitUUID(0x1805)

	// ServiceUUIDBinarySensor - Binary Sensor
	ServiceUUIDBinarySensor = New16BitUUID(0x183B)

	// ServiceUUIDMicrobitMagnetometer - micro:bit Magnetometer Service
	ServiceUUIDMicrobitMagnetometer = NewUUID([16]byte{0xe9,0x5d,0xf2,0xd8,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})

	// ServiceUUIDMicrobitTemperature - micro:bit Temperature Service
	ServiceUUIDMicrobitTemperature = NewUUID([16]byte{0xe9,0x5d,0x61,0x00,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})

	// ServiceUUIDContinuousGlucoseMonitoring - Continuous Glucose Monitoring
	ServiceUUIDContinuousGlucoseMonitoring = New16BitUUID(0x181F)

	// ServiceUUIDHTTPProxy - HTTP Proxy
	ServiceUUIDHTTPProxy = New16BitUUID(0x1823)

	// ServiceUUIDTxPower - Tx Power
	ServiceUUIDTxPower = New16BitUUID(0x1804)

	// ServiceUUIDBasicAudioAnnouncement - Basic Audio Announcement
	ServiceUUIDBasicAudioAnnouncement = New16BitUUID(0x1851)

	// ServiceUUIDLEGOWirelessProtocolV3Bootloader - LEGO® Wireless Protocol v3 Bootloader Service
	ServiceUUIDLEGOWirelessProtocolV3Bootloader = NewUUID([16]byte{0x00,0x00,0x16,0x25,0x12,0x12,0xef,0xde,0x16,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,})

	// ServiceUUIDCyclingPower - Cycling Power
	ServiceUUIDCyclingPower = New16BitUUID(0x1818)

	// ServiceUUIDConstantToneExtension - Constant Tone Extension
	ServiceUUIDConstantToneExtension = New16BitUUID(0x184A)

	// ServiceUUIDMicrobitLED - micro:bit LED Service
	ServiceUUIDMicrobitLED = NewUUID([16]byte{0xe9,0x5d,0xd9,0x1d,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})

	// ServiceUUIDAdafruitTemperature - Adafruit Temperature Service
	ServiceUUIDAdafruitTemperature = NewUUID([16]byte{0xad,0xaf,0x01,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDReconnectionConfiguration - Reconnection Configuration
	ServiceUUIDReconnectionConfiguration = New16BitUUID(0x1829)

	// ServiceUUIDScanParameters - Scan Parameters
	ServiceUUIDScanParameters = New16BitUUID(0x1813)

	// ServiceUUIDPhilipsHueLightControl - Philips Hue Light Control Service
	ServiceUUIDPhilipsHueLightControl = NewUUID([16]byte{0x93,0x2c,0x32,0xbd,0x00,0x00,0x47,0xa2,0x83,0x5a,0xa8,0xd4,0x55,0xb8,0x59,0xdd,})

	// ServiceUUIDNordicUART - Nordic UART Service
	ServiceUUIDNordicUART = NewUUID([16]byte{0x6e,0x40,0x00,0x01,0xb5,0xa3,0xf3,0x93,0xe0,0xa9,0xe5,0x0e,0x24,0xdc,0xca,0x9e,})

	// ServiceUUIDEnvironmentalSensing - Environmental Sensing
	ServiceUUIDEnvironmentalSensing = New16BitUUID(0x181A)

	// ServiceUUIDObjectTransfer - Object Transfer Service
	ServiceUUIDObjectTransfer = New16BitUUID(0x1825)

	// ServiceUUIDAppleMedia - Apple Media Service
	ServiceUUIDAppleMedia = NewUUID([16]byte{0x89,0xd3,0x50,0x2b,0x0f,0x36,0x43,0x3a,0x8e,0xf4,0xc5,0x02,0xad,0x55,0xf8,0xdc,})

	// ServiceUUIDMeshProxy - Mesh Proxy Service
	ServiceUUIDMeshProxy = New16BitUUID(0x1828)

	// ServiceUUIDVolumeControl - Volume Control
	ServiceUUIDVolumeControl = New16BitUUID(0x1844)

	// ServiceUUIDAppleNotificationCenter - Apple Notification Center Service
	ServiceUUIDAppleNotificationCenter = NewUUID([16]byte{0x79,0x05,0xf4,0x31,0xb5,0xce,0x4e,0x99,0xa4,0x0f,0x4b,0x1e,0x12,0x2d,0x00,0xd0,})

	// ServiceUUIDThingyConfiguration - Thingy Configuration Service
	ServiceUUIDThingyConfiguration = NewUUID([16]byte{0xef,0x68,0x01,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,})

	// ServiceUUIDNordicStatusMessage - Nordic Status Message Service
	ServiceUUIDNordicStatusMessage = NewUUID([16]byte{0x57,0xa7,0x00,0x00,0x93,0x50,0x11,0xed,0xa1,0xeb,0x02,0x42,0xac,0x12,0x00,0x02,})

	// ServiceUUIDBloodPressure - Blood Pressure
	ServiceUUIDBloodPressure = New16BitUUID(0x1810)

	// ServiceUUIDBodyComposition - Body Composition
	ServiceUUIDBodyComposition = New16BitUUID(0x181B)

	// ServiceUUIDPhoneAlertStatus - Phone Alert Status Service
	ServiceUUIDPhoneAlertStatus = New16BitUUID(0x180E)

	// ServiceUUIDPulseOximeter - Pulse Oximeter Service
	ServiceUUIDPulseOximeter = New16BitUUID(0x1822)

	// ServiceUUIDThingyUI - Thingy UI Service
	ServiceUUIDThingyUI = NewUUID([16]byte{0xef,0x68,0x03,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,})

	// ServiceUUIDTexasInstrumentsOvertheAirDownloadOAD - Texas Instruments Over-the-Air Download (OAD) Service
	ServiceUUIDTexasInstrumentsOvertheAirDownloadOAD = NewUUID([16]byte{0xf0,0x00,0xff,0xc0,0x04,0x51,0x40,0x00,0xb0,0x00,0x00,0x00,0x00,0x00,0x00,0x00,})

	// ServiceUUIDNordicSensorHub - Nordic Sensor Hub Service
	ServiceUUIDNordicSensorHub = NewUUID([16]byte{0xa5,0xb4,0x63,0x52,0x9d,0x13,0x47,0x9f,0x9f,0xcb,0x3d,0xcd,0xf0,0xa1,0x3f,0x4d,})

	// ServiceUUIDAudioInputControl - Audio Input Control
	ServiceUUIDAudioInputControl = New16BitUUID(0x1843)

	// ServiceUUIDDeviceTime - Device Time
	ServiceUUIDDeviceTime = New16BitUUID(0x1847)

	// ServiceUUIDExperimentalButtonlessDFU - Experimental Buttonless DFU Service
	ServiceUUIDExperimentalButtonlessDFU = NewUUID([16]byte{0x8e,0x40,0x00,0x01,0xf3,0x15,0x4f,0x60,0x9f,0xb8,0x83,0x88,0x30,0xda,0xea,0x50,})

	// ServiceUUIDAdafruitLight - Adafruit Light Service
	ServiceUUIDAdafruitLight = NewUUID([16]byte{0xad,0xaf,0x03,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDMicrobitDFUControl - micro:bit DFU Control Service
	ServiceUUIDMicrobitDFUControl = NewUUID([16]byte{0xe9,0x5d,0x93,0xb0,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})

	// ServiceUUIDLegacyDFU - Legacy DFU Service
	ServiceUUIDLegacyDFU = NewUUID([16]byte{0x00,0x00,0x15,0x30,0x12,0x12,0xef,0xde,0x15,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,})

	// ServiceUUIDFileTransferByAdafruit - File Transfer Service by Adafruit
	ServiceUUIDFileTransferByAdafruit = New16BitUUID(0xFEBB)

	// ServiceUUIDAdafruitAccelerometer - Adafruit Accelerometer Service
	ServiceUUIDAdafruitAccelerometer = NewUUID([16]byte{0xad,0xaf,0x02,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDAdafruitButton - Adafruit Button Service
	ServiceUUIDAdafruitButton = NewUUID([16]byte{0xad,0xaf,0x06,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDCyclingSpeedAndCadence - Cycling Speed and Cadence
	ServiceUUIDCyclingSpeedAndCadence = New16BitUUID(0x1816)

	// ServiceUUIDTransportDiscovery - Transport Discovery
	ServiceUUIDTransportDiscovery = New16BitUUID(0x1824)

	// ServiceUUIDMicrophoneControl - Microphone Control
	ServiceUUIDMicrophoneControl = New16BitUUID(0x184D)

	// ServiceUUIDGamingAudio - Gaming Audio
	ServiceUUIDGamingAudio = New16BitUUID(0x1858)

	// ServiceUUIDUserData - User Data
	ServiceUUIDUserData = New16BitUUID(0x181C)

	// ServiceUUIDFastPair - Fast Pair Service
	ServiceUUIDFastPair = New16BitUUID(0xFE2C)

	// ServiceUUIDExposureNotification - Exposure Notification Service
	ServiceUUIDExposureNotification = New16BitUUID(0xFD6F)

	// ServiceUUIDAdafruitGyroscope - Adafruit Gyroscope Service
	ServiceUUIDAdafruitGyroscope = NewUUID([16]byte{0xad,0xaf,0x04,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDHeliumHotspotCustom - Helium Hotspot Custom Service
	ServiceUUIDHeliumHotspotCustom = NewUUID([16]byte{0x0f,0xda,0x92,0xb2,0x44,0xa2,0x4a,0xf2,0x84,0xf5,0xfa,0x68,0x2b,0xaa,0x2b,0x8d,})

	// ServiceUUIDHealthThermometer - Health Thermometer
	ServiceUUIDHealthThermometer = New16BitUUID(0x1809)

	// ServiceUUIDIndoorPositioning - Indoor Positioning
	ServiceUUIDIndoorPositioning = New16BitUUID(0x1821)

	// ServiceUUIDLinkLoss - Link Loss
	ServiceUUIDLinkLoss = New16BitUUID(0x1803)

	// ServiceUUIDLocationAndNavigation - Location and Navigation
	ServiceUUIDLocationAndNavigation = New16BitUUID(0x1819)

	// ServiceUUIDTelephoneBearer - Telephone Bearer
	ServiceUUIDTelephoneBearer = New16BitUUID(0x184B)

	// ServiceUUIDGenericTelephoneBearer - Generic Telephone Bearer
	ServiceUUIDGenericTelephoneBearer = New16BitUUID(0x184C)

	// ServiceUUIDGlucose - Glucose
	ServiceUUIDGlucose = New16BitUUID(0x1808)

	// ServiceUUIDCoordinatedSetIdentification - Coordinated Set Identification
	ServiceUUIDCoordinatedSetIdentification = New16BitUUID(0x1846)

	// ServiceUUIDMediaControl - Media Control
	ServiceUUIDMediaControl = New16BitUUID(0x1848)

	// ServiceUUIDAdafruitHumidity - Adafruit Humidity Service
	ServiceUUIDAdafruitHumidity = NewUUID([16]byte{0xad,0xaf,0x07,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDPublishedAudioCapabilities - Published Audio Capabilities
	ServiceUUIDPublishedAudioCapabilities = New16BitUUID(0x1850)

	// ServiceUUIDMicrobitButton - micro:bit Button Service
	ServiceUUIDMicrobitButton = NewUUID([16]byte{0xe9,0x5d,0x98,0x82,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})

	// ServiceUUIDAdafruitColor - Adafruit Color Service
	ServiceUUIDAdafruitColor = NewUUID([16]byte{0xad,0xaf,0x0a,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})

	// ServiceUUIDHeartRate - Heart Rate
	ServiceUUIDHeartRate = New16BitUUID(0x180D)

	// ServiceUUIDReferenceTimeUpdate - Reference Time Update Service
	ServiceUUIDReferenceTimeUpdate = New16BitUUID(0x1806)

	// ServiceUUIDVolumeOffsetControl - Volume Offset Control
	ServiceUUIDVolumeOffsetControl = New16BitUUID(0x1845)

	// ServiceUUIDMeshProxySolicitation - Mesh Proxy Solicitation
	ServiceUUIDMeshProxySolicitation = New16BitUUID(0x1859)

	// ServiceUUIDEddystoneConfiguration - Eddystone Configuration Service
	ServiceUUIDEddystoneConfiguration = NewUUID([16]byte{0xa3,0xc8,0x75,0x00,0x8e,0xd3,0x4b,0xdf,0x8a,0x39,0xa0,0x1b,0xeb,0xed,0xe2,0x95,})

	// ServiceUUIDBleconAdvertising - Blecon Advertising Service
	ServiceUUIDBleconAdvertising = New16BitUUID(0xFD0D)

	// ServiceUUIDGenericAttribute - Generic Attribute
	ServiceUUIDGenericAttribute = New16BitUUID(0x1801)

	// ServiceUUIDPhysicalActivityMonitor - Physical Activity Monitor
	ServiceUUIDPhysicalActivityMonitor = New16BitUUID(0x183E)

	// ServiceUUIDElectronicShelfLabel - Electronic Shelf Label
	ServiceUUIDElectronicShelfLabel = New16BitUUID(0x1857)

	// ServiceUUIDNordicLEDAndButton - Nordic LED and Button Service
	ServiceUUIDNordicLEDAndButton = NewUUID([16]byte{0x00,0x00,0x15,0x23,0x12,0x12,0xef,0xde,0x15,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,})

	// ServiceUUIDNordicWiFiProvisioning - Nordic Wi-Fi Provisioning Service
	ServiceUUIDNordicWiFiProvisioning = NewUUID([16]byte{0x14,0x38,0x78,0x00,0x13,0x0c,0x49,0xe7,0xb8,0x77,0x28,0x81,0xc8,0x9c,0xb2,0x58,})

	// ServiceUUIDSecureDFU - Secure DFU Service
	ServiceUUIDSecureDFU = New16BitUUID(0xFE59)

)

func init() {

	ServiceesInfoByUUID[New16BitUUID(0x1856)] =  ServiceInfo{
		Name:       "Public Broadcast Announcement",
		Identifier: "org.bluetooth.service.public_broadcast_announcement",
		UUID:       New16BitUUID(0x1856),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x05,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Magnetometer Service",
		Identifier: "com.adafruit.service.magnetometer",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x05,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1807)] =  ServiceInfo{
		Name:       "Next DST Change Service",
		Identifier: "org.bluetooth.service.next_dst_change",
		UUID:       New16BitUUID(0x1807),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1802)] =  ServiceInfo{
		Name:       "Immediate Alert",
		Identifier: "org.bluetooth.service.immediate_alert",
		UUID:       New16BitUUID(0x1802),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1827)] =  ServiceInfo{
		Name:       "Mesh Provisioning Service",
		Identifier: "org.bluetooth.service.mesh_provisioning",
		UUID:       New16BitUUID(0x1827),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xef,0x68,0x05,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,})] =  ServiceInfo{
		Name:       "Thingy Sound Service",
		Identifier: "com.nordicsemi.service.thingy.sound",
		UUID:       NewUUID([16]byte{0xef,0x68,0x05,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[New16BitUUID(0xFEAA)] =  ServiceInfo{
		Name:       "Eddystone",
		Identifier: "com.google.service.eddystone",
		UUID:       New16BitUUID(0xFEAA),
		Source:     "google",
	}

	ServiceesInfoByUUID[New16BitUUID(0x180A)] =  ServiceInfo{
		Name:       "Device Information",
		Identifier: "org.bluetooth.service.device_information",
		UUID:       New16BitUUID(0x180A),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1820)] =  ServiceInfo{
		Name:       "Internet Protocol Support Service",
		Identifier: "org.bluetooth.service.internet_protocol_support",
		UUID:       New16BitUUID(0x1820),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xe9,0x5d,0x07,0x53,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})] =  ServiceInfo{
		Name:       "micro:bit Accelerometer Service",
		Identifier: "org.microbit.service.accelerometer",
		UUID:       NewUUID([16]byte{0xe9,0x5d,0x07,0x53,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,}),
		Source:     "microbit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xef,0x68,0x04,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,})] =  ServiceInfo{
		Name:       "Thingy Motion Service",
		Identifier: "com.nordicsemi.service.thingy.motion",
		UUID:       NewUUID([16]byte{0xef,0x68,0x04,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x0b,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Sound Service",
		Identifier: "com.adafruit.service.sound",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x0b,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1849)] =  ServiceInfo{
		Name:       "Generic Media Control",
		Identifier: "org.bluetooth.service.control.generic_media",
		UUID:       New16BitUUID(0x1849),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1815)] =  ServiceInfo{
		Name:       "Automation IO",
		Identifier: "org.bluetooth.service.automation_io",
		UUID:       New16BitUUID(0x1815),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x184E)] =  ServiceInfo{
		Name:       "Audio Stream Control",
		Identifier: "org.bluetooth.service.control.audio_stream",
		UUID:       New16BitUUID(0x184E),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xe9,0x5d,0x93,0xaf,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})] =  ServiceInfo{
		Name:       "micro:bit Event Service",
		Identifier: "org.microbit.service.event",
		UUID:       NewUUID([16]byte{0xe9,0x5d,0x93,0xaf,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,}),
		Source:     "microbit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1812)] =  ServiceInfo{
		Name:       "Human Interface Device",
		Identifier: "org.bluetooth.service.human_interface_device",
		UUID:       New16BitUUID(0x1812),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1854)] =  ServiceInfo{
		Name:       "Hearing Access",
		Identifier: "org.bluetooth.service.hearing_access",
		UUID:       New16BitUUID(0x1854),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x180F)] =  ServiceInfo{
		Name:       "Battery Service",
		Identifier: "org.bluetooth.service.battery_service",
		UUID:       New16BitUUID(0x180F),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1852)] =  ServiceInfo{
		Name:       "Broadcast Audio Announcement",
		Identifier: "org.bluetooth.service.audio.broadcast_announcement",
		UUID:       New16BitUUID(0x1852),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1853)] =  ServiceInfo{
		Name:       "Common Audio",
		Identifier: "org.bluetooth.service.audio.common",
		UUID:       New16BitUUID(0x1853),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1800)] =  ServiceInfo{
		Name:       "Generic Access",
		Identifier: "org.bluetooth.service.generic_access",
		UUID:       New16BitUUID(0x1800),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0xFE0F)] =  ServiceInfo{
		Name:       "Signify Netherlands B.V. (formerly Philips Lighting) Service",
		Identifier: "com.philips-hue.service.signify_netherlands",
		UUID:       New16BitUUID(0xFE0F),
		Source:     "philips-hue",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xe2,0xa0,0x00,0x01,0xec,0x31,0x4e,0xc3,0xa9,0x7a,0x1c,0x34,0xd8,0x7e,0x98,0x78,})] =  ServiceInfo{
		Name:       "Edge Impulse Remote Management Service",
		Identifier: "com.nordicsemi.service.edge_impulse",
		UUID:       NewUUID([16]byte{0xe2,0xa0,0x00,0x01,0xec,0x31,0x4e,0xc3,0xa9,0x7a,0x1c,0x34,0xd8,0x7e,0x98,0x78,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x08,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Barometric Service",
		Identifier: "com.adafruit.service.barometric",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x08,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1811)] =  ServiceInfo{
		Name:       "Alert Notification Service",
		Identifier: "org.bluetooth.service.alert_notification",
		UUID:       New16BitUUID(0x1811),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x181D)] =  ServiceInfo{
		Name:       "Weight Scale",
		Identifier: "org.bluetooth.service.weight_scale",
		UUID:       New16BitUUID(0x181D),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x183C)] =  ServiceInfo{
		Name:       "Emergency Configuration",
		Identifier: "org.bluetooth.service.emergency_configuration",
		UUID:       New16BitUUID(0x183C),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xb8,0x84,0x3a,0xdd,0x00,0x00,0x4a,0xa1,0x87,0x94,0xc3,0xf4,0x62,0x03,0x0b,0xda,})] =  ServiceInfo{
		Name:       "Philips Hue Light Update Service",
		Identifier: "com.philips-hue.service.light_update",
		UUID:       NewUUID([16]byte{0xb8,0x84,0x3a,0xdd,0x00,0x00,0x4a,0xa1,0x87,0x94,0xc3,0xf4,0x62,0x03,0x0b,0xda,}),
		Source:     "philips-hue",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x0e,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Proximity Service",
		Identifier: "com.adafruit.service.proximity",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x0e,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x183A)] =  ServiceInfo{
		Name:       "Insulin Delivery",
		Identifier: "org.bluetooth.service.insulin_delivery",
		UUID:       New16BitUUID(0x183A),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1855)] =  ServiceInfo{
		Name:       "Telephony and Media Audio",
		Identifier: "org.bluetooth.service.telephony_and_media_audio",
		UUID:       New16BitUUID(0x1855),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xe9,0x5d,0x12,0x7b,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})] =  ServiceInfo{
		Name:       "micro:bit IO Pin Service",
		Identifier: "org.microbit.service.io_pin",
		UUID:       NewUUID([16]byte{0xe9,0x5d,0x12,0x7b,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,}),
		Source:     "microbit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x00,0x00,0x16,0x23,0x12,0x12,0xef,0xde,0x16,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,})] =  ServiceInfo{
		Name:       "LEGO® Wireless Protocol v3 Hub Service",
		Identifier: "com.lego.service.lwp3.hub",
		UUID:       NewUUID([16]byte{0x00,0x00,0x16,0x23,0x12,0x12,0xef,0xde,0x16,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,}),
		Source:     "lego",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1814)] =  ServiceInfo{
		Name:       "Running Speed and Cadence",
		Identifier: "org.bluetooth.service.running_speed_and_cadence",
		UUID:       New16BitUUID(0x1814),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x184F)] =  ServiceInfo{
		Name:       "Broadcast Audio Scan",
		Identifier: "org.bluetooth.service.audio.broadcast_scan",
		UUID:       New16BitUUID(0x184F),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x8d,0x53,0xdc,0x1d,0x1d,0xb7,0x4c,0xd3,0x86,0x8b,0x8a,0x52,0x74,0x60,0xaa,0x84,})] =  ServiceInfo{
		Name:       "SMP Service",
		Identifier: "io.runtime.mcumgr.ble.smp",
		UUID:       NewUUID([16]byte{0x8d,0x53,0xdc,0x1d,0x1d,0xb7,0x4c,0xd3,0x86,0x8b,0x8a,0x52,0x74,0x60,0xaa,0x84,}),
		Source:     "apache",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x0d,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Quaternion Service",
		Identifier: "com.adafruit.service.quaternion",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x0d,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x54,0x22,0x00,0x00,0xf6,0xa5,0x40,0x07,0xa3,0x71,0x72,0x2f,0x4e,0xbd,0x84,0x36,})] =  ServiceInfo{
		Name:       "Memfault Diagnostic Service",
		Identifier: "com.memfault.service.mds",
		UUID:       NewUUID([16]byte{0x54,0x22,0x00,0x00,0xf6,0xa5,0x40,0x07,0xa3,0x71,0x72,0x2f,0x4e,0xbd,0x84,0x36,}),
		Source:     "memfault",
	}

	ServiceesInfoByUUID[New16BitUUID(0x181E)] =  ServiceInfo{
		Name:       "Bond Management Service",
		Identifier: "org.bluetooth.service.bond_management",
		UUID:       New16BitUUID(0x181E),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x7d,0xfc,0x60,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,})] =  ServiceInfo{
		Name:       "Apple Reserved Service 1",
		Identifier: "com.apple.service.7DFC6000",
		UUID:       NewUUID([16]byte{0x7d,0xfc,0x60,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,}),
		Source:     "apple",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x7d,0xfc,0x70,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,})] =  ServiceInfo{
		Name:       "Apple Reserved Service 2",
		Identifier: "com.apple.service.7DFC7000",
		UUID:       NewUUID([16]byte{0x7d,0xfc,0x70,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,}),
		Source:     "apple",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x7d,0xfc,0x80,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,})] =  ServiceInfo{
		Name:       "Apple Reserved Service 3",
		Identifier: "com.apple.service.7DFC8000",
		UUID:       NewUUID([16]byte{0x7d,0xfc,0x80,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,}),
		Source:     "apple",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x7d,0xfc,0x90,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,})] =  ServiceInfo{
		Name:       "Apple Reserved Service 4",
		Identifier: "com.apple.service.7DFC9000",
		UUID:       NewUUID([16]byte{0x7d,0xfc,0x90,0x00,0x7d,0x1c,0x49,0x51,0x86,0xaa,0x8d,0x97,0x28,0xf8,0xd6,0x6c,}),
		Source:     "apple",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xef,0x68,0x02,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,})] =  ServiceInfo{
		Name:       "Thingy Weather Station Service",
		Identifier: "com.nordicsemi.service.thingy.weather_station",
		UUID:       NewUUID([16]byte{0xef,0x68,0x02,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1826)] =  ServiceInfo{
		Name:       "Fitness Machine",
		Identifier: "org.bluetooth.service.fitness_machine",
		UUID:       New16BitUUID(0x1826),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x09,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Addressable Service",
		Identifier: "com.adafruit.service.addressable_pixel",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x09,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x0c,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Tone Service",
		Identifier: "com.adafruit.service.tone",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x0c,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1805)] =  ServiceInfo{
		Name:       "Current Time Service",
		Identifier: "org.bluetooth.service.current_time",
		UUID:       New16BitUUID(0x1805),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x183B)] =  ServiceInfo{
		Name:       "Binary Sensor",
		Identifier: "org.bluetooth.service.binary_sensor",
		UUID:       New16BitUUID(0x183B),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xe9,0x5d,0xf2,0xd8,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})] =  ServiceInfo{
		Name:       "micro:bit Magnetometer Service",
		Identifier: "org.microbit.service.magnetometer",
		UUID:       NewUUID([16]byte{0xe9,0x5d,0xf2,0xd8,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,}),
		Source:     "microbit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xe9,0x5d,0x61,0x00,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})] =  ServiceInfo{
		Name:       "micro:bit Temperature Service",
		Identifier: "org.microbit.service.temperature",
		UUID:       NewUUID([16]byte{0xe9,0x5d,0x61,0x00,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,}),
		Source:     "microbit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x181F)] =  ServiceInfo{
		Name:       "Continuous Glucose Monitoring",
		Identifier: "org.bluetooth.service.continuous_glucose_monitoring",
		UUID:       New16BitUUID(0x181F),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1823)] =  ServiceInfo{
		Name:       "HTTP Proxy",
		Identifier: "org.bluetooth.service.http_proxy",
		UUID:       New16BitUUID(0x1823),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1804)] =  ServiceInfo{
		Name:       "Tx Power",
		Identifier: "org.bluetooth.service.tx_power",
		UUID:       New16BitUUID(0x1804),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1851)] =  ServiceInfo{
		Name:       "Basic Audio Announcement",
		Identifier: "org.bluetooth.service.audio.basic_announcement",
		UUID:       New16BitUUID(0x1851),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x00,0x00,0x16,0x25,0x12,0x12,0xef,0xde,0x16,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,})] =  ServiceInfo{
		Name:       "LEGO® Wireless Protocol v3 Bootloader Service",
		Identifier: "com.lego.service.lwp3.bootloader",
		UUID:       NewUUID([16]byte{0x00,0x00,0x16,0x25,0x12,0x12,0xef,0xde,0x16,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,}),
		Source:     "lego",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1818)] =  ServiceInfo{
		Name:       "Cycling Power",
		Identifier: "org.bluetooth.service.cycling_power",
		UUID:       New16BitUUID(0x1818),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x184A)] =  ServiceInfo{
		Name:       "Constant Tone Extension",
		Identifier: "org.bluetooth.service.constant_tone_extension",
		UUID:       New16BitUUID(0x184A),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xe9,0x5d,0xd9,0x1d,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})] =  ServiceInfo{
		Name:       "micro:bit LED Service",
		Identifier: "org.microbit.service.led",
		UUID:       NewUUID([16]byte{0xe9,0x5d,0xd9,0x1d,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,}),
		Source:     "microbit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x01,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Temperature Service",
		Identifier: "com.adafruit.service.temperature",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x01,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1829)] =  ServiceInfo{
		Name:       "Reconnection Configuration",
		Identifier: "org.bluetooth.service.reconnection_configuration",
		UUID:       New16BitUUID(0x1829),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1813)] =  ServiceInfo{
		Name:       "Scan Parameters",
		Identifier: "org.bluetooth.service.scan_parameters",
		UUID:       New16BitUUID(0x1813),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x93,0x2c,0x32,0xbd,0x00,0x00,0x47,0xa2,0x83,0x5a,0xa8,0xd4,0x55,0xb8,0x59,0xdd,})] =  ServiceInfo{
		Name:       "Philips Hue Light Control Service",
		Identifier: "com.philips-hue.service.light_control",
		UUID:       NewUUID([16]byte{0x93,0x2c,0x32,0xbd,0x00,0x00,0x47,0xa2,0x83,0x5a,0xa8,0xd4,0x55,0xb8,0x59,0xdd,}),
		Source:     "philips-hue",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x6e,0x40,0x00,0x01,0xb5,0xa3,0xf3,0x93,0xe0,0xa9,0xe5,0x0e,0x24,0xdc,0xca,0x9e,})] =  ServiceInfo{
		Name:       "Nordic UART Service",
		Identifier: "com.nordicsemi.service.uart",
		UUID:       NewUUID([16]byte{0x6e,0x40,0x00,0x01,0xb5,0xa3,0xf3,0x93,0xe0,0xa9,0xe5,0x0e,0x24,0xdc,0xca,0x9e,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[New16BitUUID(0x181A)] =  ServiceInfo{
		Name:       "Environmental Sensing",
		Identifier: "org.bluetooth.service.environmental_sensing",
		UUID:       New16BitUUID(0x181A),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1825)] =  ServiceInfo{
		Name:       "Object Transfer Service",
		Identifier: "org.bluetooth.service.object_transfer",
		UUID:       New16BitUUID(0x1825),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x89,0xd3,0x50,0x2b,0x0f,0x36,0x43,0x3a,0x8e,0xf4,0xc5,0x02,0xad,0x55,0xf8,0xdc,})] =  ServiceInfo{
		Name:       "Apple Media Service",
		Identifier: "com.apple.service.media",
		UUID:       NewUUID([16]byte{0x89,0xd3,0x50,0x2b,0x0f,0x36,0x43,0x3a,0x8e,0xf4,0xc5,0x02,0xad,0x55,0xf8,0xdc,}),
		Source:     "apple",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1828)] =  ServiceInfo{
		Name:       "Mesh Proxy Service",
		Identifier: " org.bluetooth.service.mesh_proxy",
		UUID:       New16BitUUID(0x1828),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1844)] =  ServiceInfo{
		Name:       "Volume Control",
		Identifier: "org.bluetooth.service.volume.control",
		UUID:       New16BitUUID(0x1844),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x79,0x05,0xf4,0x31,0xb5,0xce,0x4e,0x99,0xa4,0x0f,0x4b,0x1e,0x12,0x2d,0x00,0xd0,})] =  ServiceInfo{
		Name:       "Apple Notification Center Service",
		Identifier: "com.apple.service.notification_center",
		UUID:       NewUUID([16]byte{0x79,0x05,0xf4,0x31,0xb5,0xce,0x4e,0x99,0xa4,0x0f,0x4b,0x1e,0x12,0x2d,0x00,0xd0,}),
		Source:     "apple",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xef,0x68,0x01,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,})] =  ServiceInfo{
		Name:       "Thingy Configuration Service",
		Identifier: "com.nordicsemi.service.thingy.configuration",
		UUID:       NewUUID([16]byte{0xef,0x68,0x01,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x57,0xa7,0x00,0x00,0x93,0x50,0x11,0xed,0xa1,0xeb,0x02,0x42,0xac,0x12,0x00,0x02,})] =  ServiceInfo{
		Name:       "Nordic Status Message Service",
		Identifier: "com.nordicsemi.service.status",
		UUID:       NewUUID([16]byte{0x57,0xa7,0x00,0x00,0x93,0x50,0x11,0xed,0xa1,0xeb,0x02,0x42,0xac,0x12,0x00,0x02,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1810)] =  ServiceInfo{
		Name:       "Blood Pressure",
		Identifier: "org.bluetooth.service.blood_pressure",
		UUID:       New16BitUUID(0x1810),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x181B)] =  ServiceInfo{
		Name:       "Body Composition",
		Identifier: "org.bluetooth.service.body_composition",
		UUID:       New16BitUUID(0x181B),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x180E)] =  ServiceInfo{
		Name:       "Phone Alert Status Service",
		Identifier: "org.bluetooth.service.phone_alert_status",
		UUID:       New16BitUUID(0x180E),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1822)] =  ServiceInfo{
		Name:       "Pulse Oximeter Service",
		Identifier: "org.bluetooth.service.pulse_oximeter",
		UUID:       New16BitUUID(0x1822),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xef,0x68,0x03,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,})] =  ServiceInfo{
		Name:       "Thingy UI Service",
		Identifier: "com.nordicsemi.service.thingy.ui",
		UUID:       NewUUID([16]byte{0xef,0x68,0x03,0x00,0x9b,0x35,0x49,0x33,0x9b,0x10,0x52,0xff,0xa9,0x74,0x00,0x42,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xf0,0x00,0xff,0xc0,0x04,0x51,0x40,0x00,0xb0,0x00,0x00,0x00,0x00,0x00,0x00,0x00,})] =  ServiceInfo{
		Name:       "Texas Instruments Over-the-Air Download (OAD) Service",
		Identifier: "com.ti.service.oad",
		UUID:       NewUUID([16]byte{0xf0,0x00,0xff,0xc0,0x04,0x51,0x40,0x00,0xb0,0x00,0x00,0x00,0x00,0x00,0x00,0x00,}),
		Source:     "ti",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xa5,0xb4,0x63,0x52,0x9d,0x13,0x47,0x9f,0x9f,0xcb,0x3d,0xcd,0xf0,0xa1,0x3f,0x4d,})] =  ServiceInfo{
		Name:       "Nordic Sensor Hub Service",
		Identifier: "com.nordicsemi.service.thingy.sensorhub",
		UUID:       NewUUID([16]byte{0xa5,0xb4,0x63,0x52,0x9d,0x13,0x47,0x9f,0x9f,0xcb,0x3d,0xcd,0xf0,0xa1,0x3f,0x4d,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1843)] =  ServiceInfo{
		Name:       "Audio Input Control",
		Identifier: "org.bluetooth.service.audio_input_control",
		UUID:       New16BitUUID(0x1843),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1847)] =  ServiceInfo{
		Name:       "Device Time",
		Identifier: "org.bluetooth.service.device_time",
		UUID:       New16BitUUID(0x1847),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x8e,0x40,0x00,0x01,0xf3,0x15,0x4f,0x60,0x9f,0xb8,0x83,0x88,0x30,0xda,0xea,0x50,})] =  ServiceInfo{
		Name:       "Experimental Buttonless DFU Service",
		Identifier: "com.nordicsemi.service.dfu.buttonless_experimental",
		UUID:       NewUUID([16]byte{0x8e,0x40,0x00,0x01,0xf3,0x15,0x4f,0x60,0x9f,0xb8,0x83,0x88,0x30,0xda,0xea,0x50,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x03,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Light Service",
		Identifier: "com.adafruit.service.light",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x03,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xe9,0x5d,0x93,0xb0,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})] =  ServiceInfo{
		Name:       "micro:bit DFU Control Service",
		Identifier: "org.microbit.service.dfu_control",
		UUID:       NewUUID([16]byte{0xe9,0x5d,0x93,0xb0,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,}),
		Source:     "microbit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x00,0x00,0x15,0x30,0x12,0x12,0xef,0xde,0x15,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,})] =  ServiceInfo{
		Name:       "Legacy DFU Service",
		Identifier: "com.nordicsemi.service.dfu.legacy",
		UUID:       NewUUID([16]byte{0x00,0x00,0x15,0x30,0x12,0x12,0xef,0xde,0x15,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[New16BitUUID(0xFEBB)] =  ServiceInfo{
		Name:       "File Transfer Service by Adafruit",
		Identifier: "com.adafruit.service.file_transfer",
		UUID:       New16BitUUID(0xFEBB),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x02,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Accelerometer Service",
		Identifier: "com.adafruit.service.accelerometer",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x02,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x06,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Button Service",
		Identifier: "com.adafruit.service.button",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x06,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1816)] =  ServiceInfo{
		Name:       "Cycling Speed and Cadence",
		Identifier: "org.bluetooth.service.cycling_speed_and_cadence",
		UUID:       New16BitUUID(0x1816),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1824)] =  ServiceInfo{
		Name:       "Transport Discovery",
		Identifier: "org.bluetooth.service.transport_discovery",
		UUID:       New16BitUUID(0x1824),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x184D)] =  ServiceInfo{
		Name:       "Microphone Control",
		Identifier: "org.bluetooth.service.control.microphone",
		UUID:       New16BitUUID(0x184D),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1858)] =  ServiceInfo{
		Name:       "Gaming Audio",
		Identifier: "org.bluetooth.service.gaming_audio",
		UUID:       New16BitUUID(0x1858),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x181C)] =  ServiceInfo{
		Name:       "User Data",
		Identifier: "org.bluetooth.service.user_data",
		UUID:       New16BitUUID(0x181C),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0xFE2C)] =  ServiceInfo{
		Name:       "Fast Pair Service",
		Identifier: "com.google.service.fast_pair",
		UUID:       New16BitUUID(0xFE2C),
		Source:     "google",
	}

	ServiceesInfoByUUID[New16BitUUID(0xFD6F)] =  ServiceInfo{
		Name:       "Exposure Notification Service",
		Identifier: "com.apple.service.contacttracing",
		UUID:       New16BitUUID(0xFD6F),
		Source:     "apple",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x04,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Gyroscope Service",
		Identifier: "com.adafruit.service.gyroscope",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x04,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x0f,0xda,0x92,0xb2,0x44,0xa2,0x4a,0xf2,0x84,0xf5,0xfa,0x68,0x2b,0xaa,0x2b,0x8d,})] =  ServiceInfo{
		Name:       "Helium Hotspot Custom Service",
		Identifier: "com.helium.service.custom",
		UUID:       NewUUID([16]byte{0x0f,0xda,0x92,0xb2,0x44,0xa2,0x4a,0xf2,0x84,0xf5,0xfa,0x68,0x2b,0xaa,0x2b,0x8d,}),
		Source:     "helium",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1809)] =  ServiceInfo{
		Name:       "Health Thermometer",
		Identifier: "org.bluetooth.service.health_thermometer",
		UUID:       New16BitUUID(0x1809),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1821)] =  ServiceInfo{
		Name:       "Indoor Positioning",
		Identifier: "org.bluetooth.service.indoor_positioning",
		UUID:       New16BitUUID(0x1821),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1803)] =  ServiceInfo{
		Name:       "Link Loss",
		Identifier: "org.bluetooth.service.link_loss",
		UUID:       New16BitUUID(0x1803),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1819)] =  ServiceInfo{
		Name:       "Location and Navigation",
		Identifier: "org.bluetooth.service.location_and_navigation",
		UUID:       New16BitUUID(0x1819),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x184B)] =  ServiceInfo{
		Name:       "Telephone Bearer",
		Identifier: "org.bluetooth.service.bearer.telephone",
		UUID:       New16BitUUID(0x184B),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x184C)] =  ServiceInfo{
		Name:       "Generic Telephone Bearer",
		Identifier: "org.bluetooth.service.bearer.generic_telephone",
		UUID:       New16BitUUID(0x184C),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1808)] =  ServiceInfo{
		Name:       "Glucose",
		Identifier: "org.bluetooth.service.glucose",
		UUID:       New16BitUUID(0x1808),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1846)] =  ServiceInfo{
		Name:       "Coordinated Set Identification",
		Identifier: "org.bluetooth.service.coordinated_set_identification",
		UUID:       New16BitUUID(0x1846),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1848)] =  ServiceInfo{
		Name:       "Media Control",
		Identifier: "org.bluetooth.service.control.media",
		UUID:       New16BitUUID(0x1848),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x07,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Humidity Service",
		Identifier: "com.adafruit.service.humidity",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x07,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1850)] =  ServiceInfo{
		Name:       "Published Audio Capabilities",
		Identifier: "org.bluetooth.service.audio.published_capabilities",
		UUID:       New16BitUUID(0x1850),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xe9,0x5d,0x98,0x82,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,})] =  ServiceInfo{
		Name:       "micro:bit Button Service",
		Identifier: "org.microbit.service.button",
		UUID:       NewUUID([16]byte{0xe9,0x5d,0x98,0x82,0x25,0x1d,0x47,0x0a,0xa0,0x62,0xfa,0x19,0x22,0xdf,0xa9,0xa8,}),
		Source:     "microbit",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xad,0xaf,0x0a,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,})] =  ServiceInfo{
		Name:       "Adafruit Color Service",
		Identifier: "com.adafruit.service.color",
		UUID:       NewUUID([16]byte{0xad,0xaf,0x0a,0x00,0xc3,0x32,0x42,0xa8,0x93,0xbd,0x25,0xe9,0x05,0x75,0x6c,0xb8,}),
		Source:     "adafruit",
	}

	ServiceesInfoByUUID[New16BitUUID(0x180D)] =  ServiceInfo{
		Name:       "Heart Rate",
		Identifier: "org.bluetooth.service.heart_rate",
		UUID:       New16BitUUID(0x180D),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1806)] =  ServiceInfo{
		Name:       "Reference Time Update Service",
		Identifier: "org.bluetooth.service.reference_time_update",
		UUID:       New16BitUUID(0x1806),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1845)] =  ServiceInfo{
		Name:       "Volume Offset Control",
		Identifier: "org.bluetooth.service.volume.offset_control",
		UUID:       New16BitUUID(0x1845),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1859)] =  ServiceInfo{
		Name:       "Mesh Proxy Solicitation",
		Identifier: "org.bluetooth.service.mesh_proxy_solicitation",
		UUID:       New16BitUUID(0x1859),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0xa3,0xc8,0x75,0x00,0x8e,0xd3,0x4b,0xdf,0x8a,0x39,0xa0,0x1b,0xeb,0xed,0xe2,0x95,})] =  ServiceInfo{
		Name:       "Eddystone Configuration Service",
		Identifier: "com.google.service.eddystone.configuration",
		UUID:       NewUUID([16]byte{0xa3,0xc8,0x75,0x00,0x8e,0xd3,0x4b,0xdf,0x8a,0x39,0xa0,0x1b,0xeb,0xed,0xe2,0x95,}),
		Source:     "google",
	}

	ServiceesInfoByUUID[New16BitUUID(0xFD0D)] =  ServiceInfo{
		Name:       "Blecon Advertising Service",
		Identifier: "dev.blecon.service.advertising",
		UUID:       New16BitUUID(0xFD0D),
		Source:     "blecon",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1801)] =  ServiceInfo{
		Name:       "Generic Attribute",
		Identifier: "org.bluetooth.service.generic_attribute",
		UUID:       New16BitUUID(0x1801),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x183E)] =  ServiceInfo{
		Name:       "Physical Activity Monitor",
		Identifier: "org.bluetooth.service.physical_activity_monitor",
		UUID:       New16BitUUID(0x183E),
		Source:     "gss",
	}

	ServiceesInfoByUUID[New16BitUUID(0x1857)] =  ServiceInfo{
		Name:       "Electronic Shelf Label",
		Identifier: "org.bluetooth.service.electronic_shelf_label",
		UUID:       New16BitUUID(0x1857),
		Source:     "gss",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x00,0x00,0x15,0x23,0x12,0x12,0xef,0xde,0x15,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,})] =  ServiceInfo{
		Name:       "Nordic LED and Button Service",
		Identifier: "com.nordicsemi.service.led_and_button",
		UUID:       NewUUID([16]byte{0x00,0x00,0x15,0x23,0x12,0x12,0xef,0xde,0x15,0x23,0x78,0x5f,0xea,0xbc,0xd1,0x23,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[NewUUID([16]byte{0x14,0x38,0x78,0x00,0x13,0x0c,0x49,0xe7,0xb8,0x77,0x28,0x81,0xc8,0x9c,0xb2,0x58,})] =  ServiceInfo{
		Name:       "Nordic Wi-Fi Provisioning Service",
		Identifier: "com.nordicsemi.service.wifi.provisioning",
		UUID:       NewUUID([16]byte{0x14,0x38,0x78,0x00,0x13,0x0c,0x49,0xe7,0xb8,0x77,0x28,0x81,0xc8,0x9c,0xb2,0x58,}),
		Source:     "nordic",
	}

	ServiceesInfoByUUID[New16BitUUID(0xFE59)] =  ServiceInfo{
		Name:       "Secure DFU Service",
		Identifier: "com.nordicsemi.service.dfu.secure",
		UUID:       New16BitUUID(0xFE59),
		Source:     "nordic",
	}

}
